[build]
  # Next.js 13+ with `output: 'export'` exports on build
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/blog"
  to = "/blog/"
  status = 301

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[redirects]]
  from = "/cms"
  to = "/cms/"
  status = 301

[build.environment]
  NODE_VERSION = "20"
