backend:
  name: github
  # GitHub App backend
  repo: keymarrow/ProTek
  branch: main
  app_id: 1859205
  # For GitHub OAuth (legacy), use client_id/base_url/auth_endpoint instead of app_id

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: tags, label: Tags, widget: list }
      - { name: category, label: Category }
      - { name: cover, label: Cover Image, widget: image, required: false }
      - { name: excerpt, label: Excerpt, widget: text, required: false }
      - { name: body, label: Body, widget: markdown }
